# Generated by Django 6.0.2 on 2026-05-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='uniq_default_address_per_user'),
        ),
    ]
